import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { Invoice, InsertInvoice } from '@shared/schema';

// Type for creating invoices - userId and invoiceNumber are auto-generated by backend
type CreateInvoiceInput = Omit<InsertInvoice, 'userId' | 'invoiceNumber'>;

export function useInvoices() {
  const queryClient = useQueryClient();

  const { data: invoices, isLoading } = useQuery<Invoice[]>({
    queryKey: ['/api/invoices'],
  });

  const createInvoiceMutation = useMutation({
    mutationFn: async (invoice: CreateInvoiceInput) => {
      const res = await apiRequest('POST', '/api/invoices', invoice);
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/invoices'] });
    },
  });

  return {
    invoices: invoices || [],
    isLoading,
    createInvoice: createInvoiceMutation.mutate,
    createInvoiceAsync: createInvoiceMutation.mutateAsync,
  };
}
